name: Ahchacha dev CI/CD

on:
  pull_request:
    types: [closed] #merge가 됐다면 동작 해라 라는뜻
  workflow_dispatch: #(2).수동 실행도 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest # (3).OS환경
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'ci1' //develop 브랜치에서 merge가 되었으면 동작해라

    steps:
      - name: Checkout #코드를 가져오는것 이름은 정형화된것이 아니라 마음대로 지어도됨
        uses: actions/checkout@v2 # (4).코드 check out //checkout의 기준 리포지토리의 최상단부터 build대상이되는것

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17 # (5).자바 설치
          distribution: 'adopt' #어떤 툴을 사용할지 신경x

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash # (6).권한 부여

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash # (7).build시작

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00" # (8).build 시점의 시간 확보

      - name: Show Current Time
        run: echo "CurrentTime=$"
        shell: bash # (9). 확보한 시간 보여주기

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}